# Generated by Django 4.2.7 on 2023-12-08 12:37

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import scrap.models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', jsonfield.fields.JSONField(default=scrap.models.default_url)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrap.city')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrap.language')),
            ],
            options={
                'unique_together': {('city', 'language')},
            },
        ),
    ]
